on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:

    name: "Build package"
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version: current
          cache: npm

      - name: "Install dependencies"
        run: | 
          npm install
          npm run install-ncc

      - name: "Build"
        run: npm run build

      - name: "Commit dist files"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ":octocat: built dist"
          file_pattern: 'dist/index.js dist/licenses.txt'
